---
title: "Renewable energy Data Visualisation"
author: "Mihnea Mihai & Catalina Coman"
date: '2022-04-03'
output: html_document
---

```{r setup, include=FALSE}
library("readxl")
library("dplyr")
library("ggplot2")
```
# Introduction

Using this dataset we aim to present an updated and meaningful report on the
share and historic evolution of renewables in the European energy mix.

Our dataset comprises information for the last 20 years on the energy
production and the sources which contributed to the energy mix.

```{r}
df <- read_excel('Data-file-Europe-Power-Sector-2020.xlsx')
summary(df)
```

``` {r}
data <- df %>%
  select(year = Year, country = Area, type = Variable, TWh = `Generation (TWh)`)
```

``` {r}
data <- as.data.frame(unclass(data), # https://statisticsglobe.com/convert-character-to-factor-in-r             
                      stringsAsFactors = TRUE)
```

```{r}
data %>%
  filter(country == "Romania") %>%
  select(!country) %>%
  group_by(year) %>%
  ggplot() +
    geom_line(aes(x = year, y = TWh, color = type))
```





















