---
title: "Energy data vis"
author: Mihnea Mihai & Catalina Coman
output:
  html_notebook:
    theme: darkly
    highlight: breezedark
    toc: true
---

The magic can be seen [here](https://energy-vis.herokuapp.com/).

```{r, echo=FALSE}
library(tidyverse)
```

```{r, file="../src/preprocess.R"}
```

```{r, file="../src/sources.R"}
```

```{r, file="../src/countries.R"}
```

```{r}
data
```
# Raw data

```{r, file="../src/raw_data.R"}
```

# Plots by country
```{r, file="../src/src_by_country.R"}
```

# Plots by year

```{r, fig.height=10}
country_by_year_by_source_lollipop <- function(year, source) {
  data %>%
    filter(Year == year, Source == source, Country != "EU27+1", Production > 0) %>%
    arrange(Production) %>%
    mutate(Country = factor(Country, levels = Country)) %>%
    ggplot(aes(Country, Production)) +
    geom_segment(
      aes(
        x = Country,
        xend = Country,
        y = 0,
        yend = Production
      ),
      color = "gold",
      size = 1
    ) +
    geom_point(size = 4, color = "gold") +
    coord_flip() +
    scale_y_continuous(labels = add.TWh) +
    labs(title = "Generated energy by source",
         subtitle = paste(source, " (", year, ")", sep = ""))
}

country_by_year_by_source_lollipop(2020, "Solar")
```

```{r, fig.height=10}
country_by_year_stacked <- function(year) {
  data %>%
    filter(Year == year, Source == source, Country != "EU27+1", Production > 0) %>%
    arrange(Production) %>%
    mutate(Country = factor(Country, levels = Country)) %>%
    ggplot(aes(Country, Production)) +
    geom_segment(
      aes(
        x = Country,
        xend = Country,
        y = 0,
        yend = Production
      ),
      color = "gold",
      size = 1
    ) +
    geom_point(size = 4, color = "gold") +
    coord_flip() +
    scale_y_continuous(labels = add.TWh) +
    labs(title = "Generated energy by source",
         subtitle = paste(source, " (", year, ")", sep = ""))
}

country_by_year_stacked(2020)
```


























